// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// enrichment_core_original
Rcpp::List enrichment_core_original(const arma::mat& x, const Rcpp::List& set_indices, const double alpha, const bool normalize, const int permute_n);
RcppExport SEXP _EnrichIntersect_enrichment_core_original(SEXP xSEXP, SEXP set_indicesSEXP, SEXP alphaSEXP, SEXP normalizeSEXP, SEXP permute_nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type set_indices(set_indicesSEXP);
    Rcpp::traits::input_parameter< const double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const bool >::type normalize(normalizeSEXP);
    Rcpp::traits::input_parameter< const int >::type permute_n(permute_nSEXP);
    rcpp_result_gen = Rcpp::wrap(enrichment_core_original(x, set_indices, alpha, normalize, permute_n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_EnrichIntersect_enrichment_core_original", (DL_FUNC) &_EnrichIntersect_enrichment_core_original, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_EnrichIntersect(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
